### ISSUE TITLE
"Newly added apps" section doesn't work 

### ISSUE THREAD

**Issue by lewdpatriot** [nyas1/Material-You-app-list#107]
Can't check the newly added apps section.

**Comment by TeaOwO** [comment]
This is because the "Newly added apps" section has been removed for some reason, See https://github.com/nyas1/Material-You-app-list/commit/cae0f050b31da8d2437d77c1a4eda5f2c8cafd07!

**Comment by lewdpatriot** [comment]
> This is because the "Newly added apps" section has been removed for some reason, See [cae0f05](https://github.com/nyas1/Material-You-app-list/commit/cae0f050b31da8d2437d77c1a4eda5f2c8cafd07)!

Is this intentional? If so, why? Please bring it back.

**Comment by GalileyGalileo** [comment]
Sorry. Added it back. Thanks to @TeaOwO.

**Comment by TeaOwO** [comment]
> Sorry. Added them back. Thanks to @TeaOwO.

You're welcome! ^_^
