### ISSUE TITLE
Dynamic Material You & Epik Material You icons

### ISSUE THREAD

**Issue by Nogooduser** [nyas1/Material-You-app-list#11]
Both icon packs support material you design and adaptive color palette. The former is a bit outdated and I'm not sure if still in active development (still has 12k icons though)

[Dynamic Material You](https://play.google.com/store/apps/details?id=iconpack.onsurface.monet)

[Epik Material You](https://play.google.com/store/apps/details?id=com.lknninex.epik)

**Comment by nyas1** [comment]
Added👍
