### ISSUE TITLE
Monet Generator isn't support Telegram theming anymore

### ISSUE THREAD

**Issue by r3p0rt3r** [nyas1/Material-You-app-list#115]
https://github.com/nyas1/Material-You-app-list#%EF%B8%8F-theming-apps
![Screenshot_20231016-102000_1](https://github.com/nyas1/Material-You-app-list/assets/147757370/34e36698-5f6b-4149-b1ae-e9c5da267abc)

**Comment by nyas1** [comment]
Fixed!
