### ISSUE TITLE
Right Messages is FOSS

### ISSUE THREAD

**Issue by kzhe2059** [nyas1/Material-You-app-list#125]
Right Messages is listed as closed source, but is [open source}](https://github.com/Goodwy/4Messages).

**Comment by kzhe2059** [comment]
Correction. Here is the right link:

https://github.com/Goodwy/Messages

**Comment by kzhe2059** [comment]
Sorry for the disorganized reply structure, but this would also apply to Goodwy's other apps, Contacts & Dialer?

**Comment by nyas1** [comment]
updated
