### ISSUE TITLE
Add Adguard for Android and AdGuard VPN apps

### ISSUE THREAD

**Issue by PraiseTheDuck** [nyas1/Material-You-app-list#131]
Since the latest updates of these apps, both fully support the dynamic theming feature. 

AdGuard for Android [release notes](https://adguard.com/en/versions/android/release.html#version-42118). 

AdGuard VPN [release notes](https://adguard-vpn.com/en/blog/adguard-vpn-v2-6-for-android.html).

**Comment by nyas1** [comment]
added
