### ISSUE TITLE
please add to this list open source music player "Namida"

### ISSUE THREAD

**Issue by SohaybKu** [nyas1/Material-You-app-list#139]
beautiful and modern Music player "[**Namida**](https://github.com/namidaco/namida)"; **One of the best music player apps ever made!** 

![collection_light_2](https://github.com/nyas1/Material-You-app-list/assets/135504660/532c3e20-544c-4203-bf33-f07231bb3619)
![collection_dark_1](https://github.com/nyas1/Material-You-app-list/assets/135504660/85eed301-d025-4e34-82b3-40f05c6afa7a)

**Comment by GalileyGalileo** [comment]
Thanks for your issue, I added it in my fork, and I believe nyas will add it too
