### ISSUE TITLE
Antennapod

### ISSUE THREAD

**Issue by Nogooduser** [nyas1/Material-You-app-list#14]
[Antennapod](https://github.com/AntennaPod/AntennaPod)'s latest beta releases (3.0.0) have material you coloring (under settings > dynamic color) and a tentative material you design update.

I say tentative because while the design is mostly material you it still has square edges here and there, the old hamburger menu navigation, and some old icons. Basically it's in a similar spot to GeometricWeather.These are of course all subject to update given it's a beta. But I'll let others be the judge on that.

**Comment by nyas1** [comment]
Added. Just tried 3.0.0beta6 and it was pretty good, hamburger menu and switches were old style. But yeah its in beta so maybe they'll update soon.
