### ISSUE TITLE
self promotion - MIUI / HyperOS Monet Project

### ISSUE THREAD

**Issue by naokoshoto** [nyas1/Material-You-app-list#142]
## Short description
An attempt to implement Material You wallpaper-based dynamic theme for MIUI / HyperOS system apps on Android 12+

It is a ton of themed MIUI / HyperOS System Apps, and made to feel look like on AOSP. We design everything from zero with Xiaomi looks in mind yet still implements Material You guidelines.

## Why is it paid?
It was free for the moment, but unfortunately with some people stealing the modules and claiming as his own, we decided to shifted to paid.

Discussion: https://t.me/MIUIMonet
Updates: https://t.me/MIUIMonetUpdate

**Comment by GalileyGalileo** [comment]
Hey! I like your project and I used it like a year ago. Can you just explain me, what the difference between free and paid versions? And what link should I add to the list(GitHub, telegram channel, etc)? Thank you

**Comment by naokoshoto** [comment]
> Hey! I like your project and I used it like a year ago. Can you just explain me, what the difference between free and paid versions? And what link should I add to the list(GitHub, telegram channel, etc)? Thank you

First of all, thank you for using our module! I'm glad that you liked it. 😊

The Free is usually one - two version behind the paid ones, and the paid ones gets the releases early, had prioritized bug reports, and more AOSP-like looks on the Premium plans. Also, we drop some experimental stuffs at the Donators support group on Telegram.

Also, for the links, I'd prefer to be directed to telegram as we are more active there.

Thank you 🙏✨

**Comment by naokoshoto** [comment]
> Why does photo app show as this? ![Screenshot_2024-02-23-20-52-16-366_com.miui.gallery-edit.jpg](https://private-user-images.githubusercontent.com/160399165/307326684-d5e219ea-8e50-4b59-a84c-2dc03f875a0a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDU1MjksIm5iZiI6MTcxMDYwNTIyOSwicGF0aCI6Ii8xNjAzOTkxNjUvMzA3MzI2Njg0LWQ1ZTIxOWVhLThlNTAtNGI1OS1hODRjLTJkYzAzZjg3NWEwYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNjA3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzI0MmRhNDQ1NDkzYmVhYjRhN2ZlMDU0YmIxYTJkOGRlMDUzZWJkNGYxYmU0YTQ2ZDI3MTFkOTI4ZDAxMjhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K_Fdg3S5tiy2B6Q1fPa2vGmopJfEVMnEVdZCURLhF6k)

Sorry for the very late reply, if you're on free version, it wasn't compatible properly to the newer version of Gallery app
