### ISSUE TITLE
Criteria for "Best M3 apps"

### ISSUE THREAD

**Issue by Nek-12** [nyas1/Material-You-app-list#149]
What was the reasoning behind removing Respawn from best M3 apps, and if some criteria were violated, what are the criteria for that list?

Removed in commit https://github.com/nyas1/Material-You-app-list/commit/a608c09ecb63e64ea7a98d7be8c6283e45fcc1ca

**Comment by nyas1** [comment]
Hi, the reason behind removing Respawn was that it has some inconsistencies with some design elements. So people suggested that we should remove it. In my opinion Respawn has a great design but not by material you standards. Hope you understand.

Some screenshots for reference and comparison:
![1708245264_1708244783_Screenshot_20240218-135613](https://github.com/nyas1/Material-You-app-list/assets/85426900/b80c63a8-b643-4766-aa44-8e718de0d158)
![1708245021_Screenshot_20240218-140021](https://github.com/nyas1/Material-You-app-list/assets/85426900/fa7eb74d-9b91-4d13-8fd4-8b5c4945fd04)
![1708245027_Screenshot_20240218-140026](https://github.com/nyas1/Material-You-app-list/assets/85426900/306f1131-c4a4-43e8-bbb9-740d70fee154)

**Comment by Nek-12** [comment]
I agree, thank you. My original question was - what are the criteria? Despite following M3 our team still tries to preserve brand identity - that's why not all guidelines are being followed. I'm curious to learn what is being evaluated here. The screenshots you posted aren't showing clearly what is different compared to M3 spec

**Comment by nyas1** [comment]
> Some conscious decisions we made are:
> 
>     1. Circle shapes instead of squircles
> 
>     2. Custom menu item design and layout
> 
>     3. The use of shaders
> 
>     4. Non-expandable, non-scrollable headers
> 
>     5. Custom search field design.
> 
> 
> Are you referring to those in your screenshots?

Yes, I am indeed talking about those and I completely understand that you made changes to preserve your brand identity. Respawn's design is good and unique but all the other apps in the "Best" section thoroughly follow md3 guidelines. That's why I had to remove Respawn.

**Comment by Nek-12** [comment]
I see. Then our goal may not be to follow M3 guidelines as strictly as needed for this list
