### ISSUE TITLE
FairEmail isn't Material You

### ISSUE THREAD

**Issue by anton0kurilov** [nyas1/Material-You-app-list#16]
![Screenshot_20230318-183500.png](https://user-images.githubusercontent.com/8565767/226103132-0d68b866-616e-4b28-a6c8-158adacc42f6.png)

**Comment by baraary** [comment]
Yes it is.

![Uploading Screenshot_20230318-192510_FairEmail.png…]()

**Comment by baraary** [comment]
Yes it is.:

![Screenshot_20230318-192510_FairEmail.png](https://user-images.githubusercontent.com/4853984/226116668-95bcb206-57bd-426b-b528-7754da8e2c0b.png)

**Comment by nyas1** [comment]
You need to enable it in settings
![Screenshot_20230318-212049](https://user-images.githubusercontent.com/85426900/226116677-baee7068-e6ed-4c46-aafe-ec9b2ecb071b.png)
