### ISSUE TITLE
Create Spreadsheet

### ISSUE THREAD

**Issue by Synaptic149** [nyas1/Material-You-app-list#172]
Should someone (I can do this as well) make a sheet or table for this list to make it easier to look through?

**Comment by Synaptic149** [comment]
Or make a JSON file

**Comment by nyas1** [comment]
I don't understand. It already has a table of contents, you can search through list with ctrl+f, what else would make it easier to look through?🤔

**Comment by JustAdreamerFL** [comment]
Notion website I would guess😅😂
