### ISSUE TITLE
Add heliboard, ltt.rs

### ISSUE THREAD

**Issue by Henry-Hiles** [nyas1/Material-You-app-list#181]
- Ltt.rs, JMAP Email Client: https://ltt.rs

**Comment by Henry-Hiles** [comment]
Oh, heliboard too: https://github.com/Helium314/HeliBoard

**Comment by Henry-Hiles** [comment]
Also, I believe Vivaldi isn't properly FOSS

**Comment by nyas1** [comment]
added and updated
