### ISSUE TITLE
Add Widgeet - Google Play Store.

### ISSUE THREAD

**Issue by Grassism1d** [nyas1/Material-You-app-list#204]
Hello I am new to this list and was just seeing it. I'm not sure if it's only for apps but I have a great widget material you app that is on the play store. The app is literally called Widgeet and includes :
music widgets
Clock widgets (with analog clock)
Photo widgets (you can add your own)
Storage widgets (memory, storage, and even time spent on app widgets)
There's probably more but I forgot. I'm going to link the app in the description. It's a great material you app **ESPECIALLY** if it's found casually on the playstore and not just a kwgt apk. I'm going to link the app in the description. (Mobile only I should prob mention but idk)

https://play.google.com/store/apps/details?id=art.widgeet.android

**Comment by nyas1** [comment]
added👍
