### ISSUE TITLE
Keyguard is not FOSS

### ISSUE THREAD

**Issue by WesleyBryie** [nyas1/Material-You-app-list#223]
Despite Keyguard-App's source being available on GitHub, it is under an all rights reserved license, and thus not FOSS.

**Comment by nyas1** [comment]
Fixed. I guess it will go obsolete soon cuz bitwarden official with md3 is here anyways😼

**Comment by WesleyBryie** [comment]
Well, there's always room for third party clients IMO.

**Comment by ngocanhtve** [comment]
> bitwarden official with md3 is here anyways

Can i know when?

**Comment by nyas1** [comment]
> Can i know when?

It's already out in beta phase https://community.bitwarden.com/t/about-the-beta-program/39185
also you can join our telegram, I always share the news there.

**Comment by WesleyBryie** [comment]
Vaultwarden is broken on it though, which sucks.



Best,
Wesley Bryie Student | he/him
Email me: ***@***.******@***.***>
[Discord]<https://discord.com/users/812822472838873118>[GitHub]<https://github.com/wesleybryie>[Check Out My Website]<https://wesbryie.com>
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

________________________________
