### ISSUE TITLE
I have developed some apps with Material3/You interface

### ISSUE THREAD

**Issue by JGeek00** [nyas1/Material-You-app-list#24]
Hi everyone. I just wanted to share the applications I developed. All three applications are developed with Flutter and they follow as closely as possible the Material 3 guidelines. Also they support dynamic theming. All three apps are completely free of purchases or subscriptions, ads and tracking, and they are open source. Hope you find them useful.

#### AdGuard Home Manager
An AdGuard Home client (requires an AdGuard Home server). It allows you to manage your AdGuard Home server from your smartphone.
[Google Play Store](https://play.google.com/store/apps/details?id=com.jgeek00.adguard_home_manager) | [GitHub](https://github.com/JGeek00/adguard-home-manager)

#### My Server Status 
This application shows you realtime information about your home server's hardware. It requires to have installed the API on your server to work.
[Google Play Store](https://play.google.com/store/apps/details?id=com.jgeek00.my_server_status) | [GitHub](https://github.com/JGeek00/my-server-status-app)

#### DroidHole
This is a Pi-hole client (requires a Pi-hole server). It allows you to manage your Pi-hole server from your smartphone.
[Google Play Store](https://play.google.com/store/apps/details?id=com.jgeek00.droid_hole) | [GitHub](https://github.com/JGeek00/droid-hole)

**Comment by nyas1** [comment]
Adding all of them😁👍
