### ISSUE TITLE
Add some apps

### ISSUE THREAD

**Issue by trlef19** [nyas1/Material-You-app-list#241]
- [Eternity for Lemmy ](https://codeberg.org/Bazsalanszky/Eternity)
- [Spark mail](https://play.google.com/store/apps/details?id=com.readdle.spark&hl=en_US)

**Comment by Anthonyy232** [comment]
Not sure if it's appropriate to post here, but I didn't want to create spam so I'll add mine here too.

[Paperize](https://github.com/Anthonyy232/Paperize) (disclaimer: I'm the dev)
