### ISSUE TITLE
Mark Bunny as development paused

### ISSUE THREAD

**Issue by RWCoding58** [nyas1/Material-You-app-list#243]
Bunny (one of the Discord clients) is currently in maintenance-only mode since its lead developer is facing some personal issues, so the 🪦 symbol might need to be added to it. 

screenshot of their latest announcement:
![Screenshot_20240926_215731](https://github.com/user-attachments/assets/c2e5b05b-14dc-44db-bea9-e4f73c9cfa60)

**Comment by nyas1** [comment]
done
