### ISSUE TITLE
DangoPlayer is not foss

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [nyas1/Material-You-app-list#25]
As stated here: https://github.com/brunochanrio/DangoPlayer/issues/2

**Comment by zoroya1** [comment]
> As stated here: https://github.com/brunochanrio/DangoPlayer/issues/2

Well, that is sad, I was using dango and aurora store notified about the update but GitHub had no update so I was in doubt but this clears that.

Do you know any other IPTV players which have MY or MDY ? TIA...

**Comment by IdkWhatToCallMe123** [comment]
> Do you know any other IPTV players which have MY or MDY ? TIA...

Sadly no :(

**Comment by nyas1** [comment]
Updated 🙁👍
