### ISSUE TITLE
Add Kvaesitso Launcher!

### ISSUE THREAD

**Issue by fossimprove** [nyas1/Material-You-app-list#3]
Nice list of apps, sure our phones will get filled with eye candy looks lol.

I thought to create PR, but im new to git.

https://github.com/MM2-0/Kvaesitso 

Kvaesitso is a foss launcher based on MDY.
Tbh it is one of the best looking launcher, with various features.
Unlike other apps, this launcher has MDY everywhere. 

I suggest you to try it once as well, development is super good.

**Comment by nyas1** [comment]
added👍
also, I tried it, its pretty good. But i'll continue to use lawnchair as it fits my needs well
