### ISSUE TITLE
Randomizer & Sound Meter by Code Clickers

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [nyas1/Material-You-app-list#31]
Randomizer and Sound Meter apps are both Material 3 and Dynamic Colors. There's a picker that allows you to choose if you want dynamic color or from a range of colors, as shown in the screenshot below.

_The dynamic colors switch is only available if the phone is running Android 12 or higher, else you will still have the picker, just no dynamic color option, as it was introduced in Android 12_

Both are not open source, but available on Play Store.
Randomizer: https://play.google.com/store/apps/details?id=com.codeclickers.randomizer
Sound Meter: https://play.google.com/store/apps/details?id=com.codeclickers.soundmeter

<img src="https://user-images.githubusercontent.com/54041533/233746262-b53d8233-17c2-4e1e-b4f5-f0a34b0b5135.PNG" width="300px"/>

They also both have monochrome icons, so if that is turned on in launcher settings, the icon will match the color of everything else in Android, like this:

_Only available in Android 13 and higher_
<img src="https://user-images.githubusercontent.com/54041533/233746424-17605e6d-cd0e-434d-87be-ebfd332ab3ae.jpg" width="200px"/>

_Note: I am one of the developers of both apps :)_

Thanks a lot for the work you do with this list 💛

**Comment by nyas1** [comment]
I've added both apps. Thanks😊👍
