### ISSUE TITLE
Add rkkr's Simple Keyboard

### ISSUE THREAD

**Issue by BioRider17** [nyas1/Material-You-app-list#37]
https://f-droid.org/packages/rkr.simplekeyboard.inputmethod/
https://github.com/rkkr/simple-keyboard

Able to use dynamic colors.

**Comment by GalileyGalileo** [comment]
![Screenshot_20230504-195900_exteraGram](https://user-images.githubusercontent.com/103495673/236354215-b20b55c1-3179-4e3e-b159-39f1623c9657.png)
I didn't find MD/MY.

**Comment by BioRider17** [comment]
You have to set it to system default in appearance

https://user-images.githubusercontent.com/110435075/236360050-47e53b25-0742-4f6e-aec6-e12c2b78c0f8.mp4

**Comment by GalileyGalileo** [comment]
> You have to set it to system default in appearance
> 
> https://user-images.githubusercontent.com/110435075/236360050-47e53b25-0742-4f6e-aec6-e12c2b78c0f8.mp4
> 
> 

Okay, it works! Nias1 will add(or I'll create a pull)
