### ISSUE TITLE
Looking for feedback

### ISSUE THREAD

**Issue by dgudim** [nyas1/Material-You-app-list#38]
Hey, I am the developer of [Scheduler](https://github.com/dgudim/Scheduler). I saw it in the 'Worst implementations' section. It's understandable however, as I am bad at designing things. I was just wondering, maybe you have some feedback or suggestions on improving the implementation, thanks.

**Comment by TeaEndsAcronyms** [comment]
Hey, I just checked your app and tested it! I don't know why it's in the worst implementation section... Because it's really good. The only thing I would suggest is making the logo on The three line menu also fit the material you design. :)

**Comment by dgudim** [comment]
Thanks for the kind words. :) As for the icon, yeah, maybe I'll make it adaptive

**Comment by TeaEndsAcronyms** [comment]
Thanks :)

**Comment by nyas1** [comment]
![Screenshot_20230501-153944~2](https://user-images.githubusercontent.com/85426900/236256979-e07ea69f-5a5b-4163-aad3-a0885f62c2e4.png)
![Screenshot_20230501-153817~2](https://user-images.githubusercontent.com/85426900/236257006-16ebc570-adc7-4d44-8c9c-e5b285232664.png)
![Screenshot_20230501-153807~2](https://user-images.githubusercontent.com/85426900/236257019-bda01d12-a9d5-43b0-b010-aeafbdc4cf7e.png)
this is just my opinion though 😅

**Comment by dgudim** [comment]
Much appreciated. I won't change the square  in the calendar because indicators will look ugly then, the boxed look different in the current development version, and the big icons, well, I'll see what I can do
![Screenshot_20230504_214617_Scheduler](https://user-images.githubusercontent.com/34401005/236299937-fdbd5adc-8412-4a80-bb38-d93fffe3f179.jpg)
![Screenshot_20230504_214711_Scheduler](https://user-images.githubusercontent.com/34401005/236299950-888052bb-4cd0-4f78-aa00-4581b03181a3.jpg)
Thanks for the feedback again, you can close this

**Comment by nyas1** [comment]
😄👍
