### ISSUE TITLE
Request: Mark Bromite as Inactive or Unmaintained

### ISSUE THREAD

**Issue by Indianb0y016** [nyas1/Material-You-app-list#39]
Development of Bromite has slowed to a halt and hasnt seen an update in the last few months. Until it is active again or a legitimate fork is made, its best not to list it as a safe browser to use. Excellent list though! Shame Bromite is in its current state. It was a wonderful browser

**Comment by TeaEndsAcronyms** [comment]
For a fork [look at this](https://github.com/uazo/bromite-buildtools) but I do thing bromite should be marked as `🪦 discontinued`

**Comment by keyjeyelpi** [comment]
If that's the case, then Lawnchair should be as well.

**Comment by TeaEndsAcronyms** [comment]
[Lawnchair](https://www.apkmirror.com/apk/lawnchair/) isn't discontinued?
the one on the play store is, but their apk-mirror page isn't! you can see they made [a dev (debug) update yesterday](https://www.apkmirror.com/apk/lawnchair/lawnchair-debug/lawnchair-debug-12-1-0-dev-1893-release/lawnchair-debug-12-1-0-dev-1893-android-apk-download/)

**Comment by keyjeyelpi** [comment]
> [Lawnchair](https://www.apkmirror.com/apk/lawnchair/) isn't discontinued?
> the one on the play store is, but their apk-mirror page isn't! you can see they made [a dev (debug) update](https://www.apkmirror.com/apk/lawnchair/lawnchair-debug/lawnchair-debug-12-1-0-dev-1893-release/lawnchair-debug-12-1-0-dev-1893-android-apk-download/)  yesterday
> 
> (Lawnchair 2 is on the playstore, while lawnchair 12 is on apkmirror)

Nope, if you take a look at the contents of the dev builds, they're nothing but automated updates on the dependencies. The only update that's actually been significant was adding pixel search support due to a small discussion on the TG group. Other than that, Lawnchair's been on a long hiatus.

**Comment by TeaEndsAcronyms** [comment]
In my opinion it doesn't matter whether its big or small update... still an update!
updates mean the project is not discontinued. but hey i could be wrong :)
