### ISSUE TITLE
Rkkr's simple keyboard is listed twice

### ISSUE THREAD

**Issue by BioRider17** [nyas1/Material-You-app-list#44]

**Comment by TeaEndsAcronyms** [comment]
No, they don't?

I tried they both lead to their corresponding links!

**Comment by TeaEndsAcronyms** [comment]
See this:
<img width="568" alt="Scresenst 2023-05-09 032622" src="https://github.com/nyas1/Material-You-app-list/assets/123305689/cee8b8ba-68d3-44f7-85cd-acaba0f2f013">

They both have their correct links!

**Comment by BioRider17** [comment]
My mistake, changed title to what the actual issue is
