### ISSUE TITLE
Request to add apps

### ISSUE THREAD

**Issue by ziadOUA** [nyas1/Material-You-app-list#46]
Hi !
I am the developer of [zCalc](https://github.com/ziadOUA/zCalc) and [zCard](https://github.com/ziadOUA/zCard), which are respectively forks of OpenCalc and Catima.

I improved and polished their UIs (especially for zCard) to better follow the Material 3 guidelines (with Material You support).

Thanks.

**Comment by TeaEndsAcronyms** [comment]
I've Made a pull request, also i really like the apps!

**Comment by nyas1** [comment]
> I've Made a pull request, also i really like the apps!

Thanks, Tea.
