### ISSUE TITLE
some corrections 

### ISSUE THREAD

**Issue by PranavPurwar** [nyas1/Material-You-app-list#56]
FairEmail and none of the Simple* apps provided in this list are material you or even Material 3 designed. Also you could add zCalc to MDY calculator list
and for apps like respawn, maybe you can create a tag for apps that use custom material design instead of official one since it being on Hall Of Fame misleads people about its appearance

**Comment by nyas1** [comment]
FairMail has dynamic theme.
All of the simple apps have atleast MY.
zCalc is already in list.
Okay, I'll add a tag for custom designed apps. Thanks for your suggestions.

**Comment by PranavPurwar** [comment]
Im unable to find dynamic theme option in FairEmail.
Simple notes 
![Screenshot_2023-05-28-13-51-05-055_com simplemobiletools notes pro](https://github.com/nyas1/Material-You-app-list/assets/75154889/5b98b866-08d9-4bd0-8634-c03547879904)
Simple Launcher 
![Screenshot_2023-05-28-13-51-22-952_com simplemobiletools launcher](https://github.com/nyas1/Material-You-app-list/assets/75154889/ba7dae02-9dc2-496d-88a1-9db011dcd8b5)

**Comment by nyas1** [comment]
![Screenshot_20230528-155251_FairEmail](https://github.com/nyas1/Material-You-app-list/assets/85426900/05650d4b-3378-4809-8018-66df4714c4ae)
![Screenshot_20230528-155320_FairEmail](https://github.com/nyas1/Material-You-app-list/assets/85426900/8d32ae35-51f3-4f2a-81b3-c9a452cb552e)
FairEmail👆

**Comment by nyas1** [comment]
![Screenshot_20230528-155402_Notes](https://github.com/nyas1/Material-You-app-list/assets/85426900/1d7e70f8-064b-4759-86de-6a0d4d1e8352)
![Screenshot_20230528-155415_Notes](https://github.com/nyas1/Material-You-app-list/assets/85426900/7277e200-52c5-45d3-a07c-be3e16207acb)
Simple Notes👆

**Comment by PranavPurwar** [comment]
uhh for some reason, none of them show up for me

**Comment by TeaEndsAcronyms** [comment]
What android version are you in? 'cause  Material you is only available in android 12+ maybe that's why it's not showing up? That's the only reason I could think of.

**Comment by PranavPurwar** [comment]
Android 12. Probably some manufacturers modifications.
