### ISSUE TITLE
Koduko

### ISSUE THREAD

**Issue by Poussinou** [nyas1/Material-You-app-list#6]
[Koduko](https://github.com/Mazahir26/koduko) supports Material 3 Design.

**Comment by nyas1** [comment]
was already there but the name was misspelled thanks👍

**Comment by Poussinou** [comment]
Sorry, I was searching with Ctrl+F but obviously it failed in this case

**Comment by nyas1** [comment]
I meant the name was missplled as kudoko or smthng
