### ISSUE TITLE
Add a few apps

### ISSUE THREAD

**Issue by orestis150** [nyas1/Material-You-app-list#62]
Project Themer: https://play.google.com/store/apps/details?id=com.drsants.eggproject

You IconPack:
https://play.google.com/store/apps/details?id=com.jndapp.pastel.material.you.iconpack

Adaptive You IconPack:
https://play.google.com/store/apps/details?id=com.jndapp.adaptive.material.you.iconpack

**Comment by nyas1** [comment]
Done😁👍
