### ISSUE TITLE
Please add this foss habit tracker with MDY

### ISSUE THREAD

**Issue by missyraja** [nyas1/Material-You-app-list#70]
https://github.com/ofalvai/HabitBuilder

**Comment by TeaEndsAcronyms** [comment]
It has already been added?
1: ![HabitBuilder](https://github.com/nyas1/Material-You-app-list/assets/123305689/0e35862b-5fba-4935-ab4b-98b7cd4fa393)

---

2: ![HabitBuilder2](https://github.com/nyas1/Material-You-app-list/assets/123305689/d3104a84-c7d0-4a97-a2c6-e8ee12c4c4e2)

**Comment by missyraja** [comment]
Oops 😬
