### ISSUE TITLE
MD3 style badges!

### ISSUE THREAD

**Issue by TeaEndsAcronyms** [nyas1/Material-You-app-list#71]
This is more a design thing... but, i saw this repo for md3 badges and they very recently made a [star badge](https://github.com/ziadOUA/m3-Markdown-Badges/issues/8#issuecomment-1606256744)! Its good looking (looks like a material you button) and im just recommending them. its fine if you don't add it :)

**Comment by nyas1** [comment]
Cool, it looks good but I don't like the font :/. I'll stick to the current badge for now..

**Comment by ziadOUA** [comment]
Yeah it's a weird problem regarding the loading of CSS stylesheets, so it is defaulting to an ugly font. I'm trying to fix this at the moment.

**Comment by ziadOUA** [comment]
I fixed the font issue, now it looks infinitely better, and it goes on par with my other static badges.

**Comment by TeaEndsAcronyms** [comment]
> I fixed the font issue, now it looks infinitely better, and it goes on par with my other static badges.

They look so good now! ❤️

**Comment by TeaEndsAcronyms** [comment]
Re-opened so that nyas1 could see this!

**Comment by nyas1** [comment]
Updated 🤩
