### ISSUE TITLE
Add Gramophone

### ISSUE THREAD

**Issue by rickdtc** [nyas1/Material-You-app-list#90]
# gramophone
In wip but,
## github
https://github.com/AkaneTan/Gramophone
## screenshots
![Screenshot_20230820_102022_Gramophone](https://github.com/nyas1/Material-You-app-list/assets/74096544/08dd00b7-190e-447a-9fff-ef3dfb7534ee)
![Screenshot_20230820_102006_Gramophone](https://github.com/nyas1/Material-You-app-list/assets/74096544/51e9fb56-09e6-47d2-b43f-806a47723999)
![Screenshot_20230820_102002_Gramophone](https://github.com/nyas1/Material-You-app-list/assets/74096544/e8d096ad-f498-4c7b-9497-7c34d3b372d7)

**Comment by GalileyGalileo** [comment]
Added

**Comment by rickdtc** [comment]
Let's go
