### ISSUE TITLE
Remove Etar

### ISSUE THREAD

**Issue by Mennaruuk** [nyas1/Material-You-app-list#94]
Unfortunately it's old Material Design, not Material You.

**Comment by GalileyGalileo** [comment]
Sorry, but it is Material You. It has Material You colors

**Comment by Mennaruuk** [comment]
Etar follows Material Design 2, and it doesn't implement Dynamic Color. As such, it has no place on this list.

**Comment by nyas1** [comment]
It has dynamic color, only a few elements change color but they do.

**Comment by Mennaruuk** [comment]
> It has dynamic color, only a few elements change color but they do.

A few elements changing color isn't Dynamic Color. [Dynamic Color](https://chromium.googlesource.com/chromium/src/+/main/docs/ui/android/dynamic_colors.md) is when "applications can be themed using a custom color palette extracted from the user’s wallpaper", and Etar clearly cannot do that. But you do you.

**Comment by Mennaruuk** [comment]
> It has dynamic color, only a few elements change color but they do.

A few elements changing color isn't Dynamic Color. [Dynamic Color](https://chromium.googlesource.com/chromium/src/+/main/docs/ui/android/dynamic_colors.md) is when "applications can be themed using a custom color palette extracted from the user’s wallpaper", and Etar clearly cannot do that. Etar's [source code](https://github.com/search?q=repo%3AEtar-Group%2FEtar-Calendar%20DynamicColor&type=code) does not reference DynamicColor anywhere, unlike the other apps. But you do you.
